theme: jekyll-theme-minimal
title: Sunkyoo
description: Image Processing, Computer Vision, OpenCV, Deep Learning, C/C++, Python, Java, Android, etc.
logo: /assets/image/sunkyoo_logo.jpg
show_downloads: "false"
google_analytics: UA-132973055-1